@startuml C4_Elements


!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Web-Powered Email System

Person(user, "User", "People who use the app to manage email communications.")


System_Boundary(emailApp, "Email Application", "An application for managing personal emails in the style of Microsoft Outlook."){
    System(webApp, "Web Site", "The web version of the email application.")
    System(desktopApp, "Desktop App", "Desktop App version of the email system, compatible with Windows, Mac, and Linux")
}

System(database, "Database", "Stores user credentials and all app data.")

Rel(user, webApp, "Access emails on a website")
Rel(user, desktopApp, "Access emails from a personal computer with the desktop app.")
Rel(emailApp, database, "Retrieve user data.")

@enduml
